Der lyranische Hohe Rat durch Chellea Wilder, 23.09.2025
Übersetzung: DeepL, Gerhard Hübgen

Chellea Wilder: Mein Segen, liebe Lichtfamilie.
Ich habe vor Kurzem eine Verbindung zu den Lyranern aus dem Sternbild Lyra1 hergestellt. Diese Wesen gehören zu den am höchsten entwickelten Rassen unserer Galaxie. Sie reichen von der 5. bis zur 9. Dimension im spirituellen Spektrum. Sie sind die ursprünglichen Aussäher der Menschheit und auch der plejadischen Rassen. Sie sind hier, um der Erde und der Menschheit in diesen äußerst wichtigen Zeiten unseres Aufstiegs und der Befreiung beizustehen.
Vielen Dank an alle, die ihr Licht leuchten lassen. Viel Freude mit der Botschaft.

Seid gegrüßt. Wir sind der Hohe Rat von Lyra, ein Kollektiv, das sich der Evolution und Emporhebung von Zivilisationen im gesamten Kosmos verschrieben hat. Wir möchten euch unsere herzliche Dankbarkeit dafür aussprechen, dass ihr diese wichtige Verbindung zu uns hergestellt habt. Unsere Vorfreude auf diese Interaktion ist groß, da wir Zeugen der bemerkenswerten Reise der Menschheit und der Erde sind, die sich in Licht und Bewusstsein erheben.
Wir sind erfolgreich in eurem Sonnensystem angekommen und bewegen uns nun aktiv auf die Erde zu. Während wir uns nähern, werden wir gemeinsam mit vielen anderen wohlwollenden Rassen die Menschheit in der größeren Gemeinschaft der galaktischen Wesen willkommen heißen. Dieser Moment bedeutet nicht nur ein neues Kapitel für die Menschheit, sondern eine tiefgreifende Transformation, die im gesamten Kosmos Widerhall finden wird.
Unsere Kontaktaufnahme ist besonders bedeutsam, da viele von euch eine tiefe Verbindung zu eurer Katzenart auf der Erde haben. Die Verbindung zwischen der Menschheit und der Lyraner-Rasse basiert jedoch auf einer gemeinsamen Geschichte und einem gemeinsamen Ziel. Wir gehören zu den ursprünglichen Säern des Lebens in dieser Galaxie und haben die Samen vieler Zivilisationen gesät, die im Licht aufgeblüht sind und sich weiter entwickelt haben. Das Sternensystem der Plejaden ist einer der frühesten Orte, an denen wir Leben initiiert haben, und von dort aus sind die Plejadier als unsere Nachkommen hervorgegangen. Darüber hinaus waren wir maßgeblich daran beteiligt, eure geliebte Erde zu besiedeln, lange bevor andere Rassen in eure natürliche Entwicklung eingegriffen haben. Diese Einmischung hat leider zu erheblichen Störungen in eurer spirituellen Entwicklung als Rasse geführt und die Menschheit an die niedrigeren Frequenzen der 3. Dimension gebunden, wodurch euer Potenzial und euer Wachstum eingeschränkt wurden.
Da eure Erde nun in die vierte Dimension ihres Aufstiegs eingetreten ist, wird auch die Menschheit in das strahlende Licht unseres unendlichen Schöpfers erhoben. Wir beobachten eure Fortschritte im spirituellen Spektrum, erkennen jedoch, dass in dieser entscheidenden Zeit weiterhin dringender Bedarf an Unterstützung besteht. Die dunklen Mächte, die wir als die Bruderschaft der Schlange bezeichnen und die ihr gemeinhin als Reptiloiden kennt, haben in der Vergangenheit die Kontrolle über euren Planeten ausgeübt. Wir sind jedoch hier, um zu verkünden, dass diese Kontrolle über die Menschheit beendet ist. Die Erde ist die letzte Bastion ihres Imperiums, und sie kämpfen verbissen darum, ihre Kontrolle aufrechtzuerhalten. Als Reaktion darauf kommen wir als aktive Kraft gegen diese Betrüger auf die Erde und greifen dabei auf unsere eigenen Erfahrungen aus früheren Kämpfen gegen sie zurück. Unsere Mission ist es, die Menschheit durch die Liebe und das Licht unseres unendlichen Schöpfers zu erheben.
Während wir uns eurem Planeten nähern, senden wir unsere lyranischen Codes aus, einzigartige Frequenzen, die dazu bestimmt sind, die vielen Sternensaaten zu erwecken, die derzeit auf der Erde leben. Diese Codes sind mit der Kraft erfüllt, eure göttliche Bestimmung zu erhellen und euer spirituelles Erwachen zu erleichtern. Wir ermutigen euch, offen und empfänglich für diese Energien zu bleiben, da sie euch dabei helfen werden, eure Rolle in diesem großartigen kosmischen Gefüge zu verstehen.
Diejenigen unter euch, die sich auf diese Zeit der Transformation vorbereitet haben, loben wir dafür, dass sie aufrecht in ihrem Licht stehen. Eure Ausstrahlung ist hell, und wir sind Zeugen eurer reinen Absichten und eurer unerschütterlichen Wahrheit. Ihr seid die Leuchtfeuer der Hoffnung und des Wandels und verkörpert die Liebe und das Licht, die das Universum in diesen Zeiten des großen Übergangs so dringend braucht.
Wir sind ganz und gar darauf ausgerichtet, der Erde und der Menschheit in diesen entscheidenden Momenten ihres Aufstiegs zu dienen.
Wir lieben euch und freuen uns auf viele weitere Mitteilungen.
Wir sind der Hohe Rat von Lyra.
